---
abstract: 'perl interface for Cocoa event loop.'
author:
  - 'Daisuke Murase <typester@cpan.org>'
build_requires:
  Devel::PPPort: 3.19
  ExtUtils::MakeMaker: 6.42
  ExtUtils::ParseXS: 2.21
  Test::More: 0.88
  Test::TCP: 1.11
configure_requires:
  Devel::PPPort: 3.19
  ExtUtils::MakeMaker: 6.42
distribution_type: module
generated_by: 'Module::Install version 1.00'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: Cocoa-EventLoop
no_index:
  directory:
    - inc
    - t
    - xt
requires:
  XSLoader: 0.1
resources:
  license: http://dev.perl.org/licenses/
  repository: git://github.com/typester/cocoa-eventloop-perl.git
version: 0.02
